# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_post_wordsofar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nameLength',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
