# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0004_post_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='letter',
            field=models.CharField(default='STRING', max_length=500),
        ),
    ]
