# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0006_post_word_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='word_length',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
