# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0008_remove_post_word_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nameLength',
        ),
        migrations.AddField(
            model_name='post',
            name='masterword',
            field=models.CharField(default='STRING', max_length=500),
        ),
    ]
